Updated for Magisk v19 template format.

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -1,34 +1,28 @@
 #!/sbin/sh
-##########################################################################################
-#
-# Magisk Module Template Install Script
-# by topjohnwu
-#
-##########################################################################################
-
-# Detect whether in boot mode
-ps | grep zygote | grep -v grep >/dev/null && BOOTMODE=true || BOOTMODE=false
-$BOOTMODE || ps -A 2>/dev/null | grep zygote | grep -v grep >/dev/null && BOOTMODE=true
 
 TMPDIR=/dev/tmp
-INSTALLER=$TMPDIR/install
-MAGISKBIN=/data/adb/magisk
+MOUNTPATH=/dev/magisk_img
 
 # Default permissions
 umask 022
 
 # Initial cleanup
 rm -rf $TMPDIR 2>/dev/null
-mkdir -p $INSTALLER
+mkdir -p $TMPDIR
 
 # echo before loading util_functions
 ui_print() { echo "$1"; }
 
 require_new_magisk() {
-  ui_print "*******************************"
-  ui_print " Please install Magisk v15.0+! "
-  ui_print "*******************************"
+  ui_print "***********************************"
+  ui_print " Please install the latest Magisk! "
+  ui_print "***********************************"
   exit 1
+}
+
+imageless_magisk() {
+  [ $MAGISK_VER_CODE -gt 18100 ]
+  return $?
 }
 
 ##########################################################################################
@@ -36,31 +30,26 @@ require_new_magisk() {
 ##########################################################################################
 
 OUTFD=$2
-ZIP=$3
+ZIPFILE=$3
 
 mount /data 2>/dev/null
 
-# Utility functions must exist
-[ -f $MAGISKBIN/util_functions.sh ] || require_new_magisk
-# Load utility fuctions
-. $MAGISKBIN/util_functions.sh
-
-# We can't alter magisk image live, use alternative image if required
-$BOOTMODE && IMG=/data/adb/magisk_merge.img
-# Always mount under tmp
-MOUNTPATH=$TMPDIR/magisk_img
+# Load utility functions
+if [ -f /data/adb/magisk/util_functions.sh ]; then
+  . /data/adb/magisk/util_functions.sh
+  NVBASE=/data/adb
+else
+  require_new_magisk
+fi
 
 # Preperation for flashable zips
-get_outfd
+setup_flashable
 
 # Mount partitions
 mount_partitions
 
 # Detect version and architecture
 api_level_arch_detect
-
-# You can get the Android API version from $API, the CPU architecture from $ARCH
-# Useful if you are creating Android version / platform dependent mods
 
 # Setup busybox and binaries
 $BOOTMODE && boot_actions || recovery_actions
@@ -70,22 +59,28 @@ $BOOTMODE && boot_actions || recovery_actions
 ##########################################################################################
 
 # Extract common files
-unzip -o "$ZIP" module.prop config.sh 'common/*' -d $INSTALLER >&2
+unzip -oj "$ZIPFILE" module.prop install.sh uninstall.sh 'common/*' -d $TMPDIR >&2
 
-[ ! -f $INSTALLER/config.sh ] && abort "! Unable to extract zip file!"
-# Load configurations
-. $INSTALLER/config.sh
+[ ! -f $TMPDIR/install.sh ] && abort "! Unable to extract zip file!"
+# Load install script
+. $TMPDIR/install.sh
 
-# Check the installed magisk version
-MIN_VER=`grep_prop minMagisk $INSTALLER/module.prop`
-[ ! -z $MAGISK_VER_CODE -a $MAGISK_VER_CODE -ge $MIN_VER ] || require_new_magisk
-MODID=`grep_prop id $INSTALLER/module.prop`
-MODPATH=$MOUNTPATH/$MODID
+if imageless_magisk; then
+  $BOOTMODE && MODDIRNAME=modules_update || MODDIRNAME=modules
+  MODULEROOT=$NVBASE/$MODDIRNAME
+else
+  $BOOTMODE && IMGNAME=magisk_merge.img || IMGNAME=magisk.img
+  IMG=$NVBASE/$IMGNAME
+  request_zip_size_check "$ZIPFILE"
+  mount_magisk_img
+  MODULEROOT=$MOUNTPATH
+fi
 
-# Print mod name
+MODID=`grep_prop id $TMPDIR/module.prop`
+MODPATH=$MODULEROOT/$MODID
+
 print_modname
 
-# Please leave this message in your flashable zip for credits :)
 ui_print "******************************"
 ui_print "Powered by Magisk (@topjohnwu)"
 ui_print "******************************"
@@ -94,116 +89,63 @@ ui_print "******************************"
 # Install
 ##########################################################################################
 
-# Get the variable reqSizeM. Use your own method to determine reqSizeM if needed
-request_zip_size_check "$ZIP"
-
-# This function will mount $IMG to $MOUNTPATH, and resize the image based on $reqSizeM
-mount_magisk_img
-
 # Create mod paths
 rm -rf $MODPATH 2>/dev/null
 mkdir -p $MODPATH
 
-# Extract files to system. Use your own method if needed
-ui_print "- Extracting module files..."
-unzip -o "$ZIP" 'system/*' -d $MODPATH >&2
-
 # Remove placeholder
 rm -f $MODPATH/system/placeholder 2>/dev/null
+
+# Custom uninstaller
+[ -f $TMPDIR/uninstall.sh ] && cp -af $TMPDIR/uninstall.sh $MODPATH/uninstall.sh
+
+# Auto Mount
+if imageless_magisk; then
+  $SKIPMOUNT && touch $MODPATH/skip_mount
+else
+  $SKIPMOUNT || touch $MODPATH/auto_mount
+fi
+
+# prop files
+$PROPFILE && cp -af $TMPDIR/system.prop $MODPATH/system.prop
+
+# Module info
+cp -af $TMPDIR/module.prop $MODPATH/module.prop
+if $BOOTMODE; then
+  # Update info for Magisk Manager
+  if imageless_magisk; then
+    mktouch $NVBASE/modules/$MODID/update
+    cp -af $TMPDIR/module.prop $NVBASE/modules/$MODID/module.prop
+  else
+    mktouch /sbin/.magisk/img/$MODID/update
+    cp -af $TMPDIR/module.prop /sbin/.magisk/img/$MODID/module.prop
+  fi
+fi
+
+# post-fs-data mode scripts
+$POSTFSDATA && cp -af $TMPDIR/post-fs-data.sh $MODPATH/post-fs-data.sh
+
+# service mode scripts
+$LATESTARTSERVICE && cp -af $TMPDIR/service.sh $MODPATH/service.sh
+
+on_install
 
 # Handle replace folders
 for TARGET in $REPLACE; do
   mktouch $MODPATH$TARGET/.replace
 done
 
-# Auto Mount
-$AUTOMOUNT && touch $MODPATH/auto_mount
-
-# prop files
-$PROPFILE && cp -af $INSTALLER/common/system.prop $MODPATH/system.prop
-
-# Module info
-cp -af $INSTALLER/module.prop $MODPATH/module.prop
-if $BOOTMODE; then
-  # Update info for Magisk Manager
-  mktouch /sbin/.core/img/$MODID/update
-  cp -af $INSTALLER/module.prop /sbin/.core/img/$MODID/module.prop
-fi
-
-# post-fs-data mode scripts
-$POSTFSDATA && cp -af $INSTALLER/common/post-fs-data.sh $MODPATH/post-fs-data.sh
-
-# service mode scripts
-$LATESTARTSERVICE && cp -af $INSTALLER/common/service.sh $MODPATH/service.sh
-
-ui_print "- Configuring Bixby button..."
-ui_print ""
-ui_print "Make a choice from the following functions:"
-ui_print ""
-ui_print "Camera (CAMERA)"
-ui_print "Screenshot (SYSRQ)"
-ui_print "Google Search (SEARCH)"
-ui_print "Google Voice (VOICE_ASSIST)"
-ui_print "Call (CALL)"
-ui_print "Contacts (CONTACTS)"
-ui_print "Music Player (MUSIC)"
-ui_print "Mute/Unmute Media Volume (VOLUME_MUTE)"
-ui_print "Play/Pause Media (MEDIA_PLAY_PAUSE)"
-ui_print "Next Media (MEDIA_NEXT)"
-ui_print "Recent Apps (APP_SWITCH)"
-ui_print "Open/Close Quick Settings (QPANEL_ON_OFF)"
-ui_print "Internet Browser (EXPLORER)"
-ui_print "Calendar (CALENDAR)"
-ui_print "Calculator (CALCULATOR)"
-ui_print ""
-ui_print "Use the hardware buttons to make a selection."
-ui_print ""
-
-q_and_a CAMERA SYSRQ Other
-[ -z "$CHOICE" ] && q_and_a SEARCH VOICE_ASSIST Other
-[ -z "$CHOICE" ] && q_and_a CALL CONTACTS Other
-[ -z "$CHOICE" ] && q_and_a MUSIC VOLUME_MUTE Other
-[ -z "$CHOICE" ] && q_and_a MEDIA_PLAY_PAUSE MEDIA_NEXT Other
-[ -z "$CHOICE" ] && q_and_a APP_SWITCH QPANEL_ON_OFF Other
-[ -z "$CHOICE" ] && q_and_a EXPLORER CALENDAR Other
-[ -z "$CHOICE" ] && q_and_a CALCULATOR Other
-if [ -z "$CHOICE" ]; then
-  ui_print "- No choice made. Using CAMERA."
-  CHOICE=CAMERA
-fi
-
-bl=$(getprop ro.boot.bootloader)
-
-# Device is either 4 or 5 characters long, depending on length of bootloader
-# string.
-#
-device=${bl:0:$((${#bl} - 8))}
-
-kl=/system/usr/keylayout/Generic.kl
-kl_s10=$kl.g97x
-
-# Select the right keyboard layout for this device.
-#
-if ( [ $device = G975F ] || [ $device = G973F ] || [ $device = G970F ]); then
-  mv $MODPATH$kl_s10 $MODPATH$kl
-else
-  rm $MODPATH$kl_s10
-fi
-
-sed -i -re 's/(key 703 +)[A-Z]+$/\1'$CHOICE'/' $MODPATH$kl
-
-ui_print "- Setting permissions."
+ui_print "- Setting permissions"
 set_permissions
 
 ##########################################################################################
 # Finalizing
 ##########################################################################################
 
-# Unmount magisk image and shrink if possible
-unmount_magisk_img
-
+cd /
+imageless_magisk || unmount_magisk_img
 $BOOTMODE || recovery_cleanup
-rm -rf $TMPDIR
+rm -rf $TMPDIR $MOUNTPATH
 
 ui_print "- Done"
 exit 0
